export const BLOG_CATEGORIES = [
  "All",
  "Meetings",
  "Chat",
  "Scheduling",
  "Video Sessions",
  "Security",
  "Updates",
];

export const BLOG_POSTS = [
  {
    slug: "secure-video-meetings",
    category: "Meetings",
    title: "Secure Video Meetings: Best Practices",
    excerpt:
      "How to run smoother meetings: permissions, participant controls, and reliable audio/video habits.",
    date: "Apr 2026",
    readTime: "4 min",
    content: [
      "Secure meetings start with small habits and clear controls.",
      "",
      "## Before the meeting",
      "- Share links only with the right people",
      "- Check your camera/mic permissions",
      "- Join early and test audio",
      "",
      "## During the meeting",
      "- Use participant controls if needed (mute/remove/lock)",
      "- Keep screen sharing limited to what’s necessary",
      "- If recording is enabled, confirm who has access to recordings",
      "",
      "## After the meeting",
      "- Save key notes and decisions",
      "- Share the summary with the team",
    ],
  },
  {
    slug: "group-chat-tips",
    category: "Chat",
    title: "Real‑Time Group Chat That Stays Organized",
    excerpt:
      "Simple ways to keep conversations clear with threads, files, and notifications.",
    date: "Apr 2026",
    readTime: "3 min",
    content: [
      "Group chat is powerful when it stays clean and focused.",
      "",
      "## Tips",
      "- Use short messages (one topic per message)",
      "- Share files with a quick context line",
      "- Mention people when you need action",
      "- Keep notifications on for important groups only",
    ],
  },
  {
    slug: "schedule-meetings",
    category: "Scheduling",
    title: "Schedule Meetings Like a Pro",
    excerpt:
      "Plan ahead, set reminders, and keep everyone aligned with a clean calendar workflow.",
    date: "Apr 2026",
    readTime: "3 min",
    content: [
      "Scheduling works best when it’s predictable and visible to everyone.",
      "",
      "## A simple workflow",
      "1. Pick a clear title and goal",
      "2. Set the date/time and add participants",
      "3. Add an agenda (even 3 bullets is enough)",
      "4. Send a reminder",
    ],
  },
  {
    slug: "video-sessions-library",
    category: "Video Sessions",
    title: "Record & Save: Build a Sessions Library",
    excerpt:
      "Turn meetings into a searchable knowledge base with recordings, summaries, and highlights.",
    date: "Apr 2026",
    readTime: "5 min",
    content: [
      "Recordings become valuable when they’re easy to find.",
      "",
      "## Best practices",
      "- Use consistent names for sessions",
      "- Store key sessions in a shared library",
      "- Add a short summary after each session",
    ],
  },
  {
    slug: "privacy-overview",
    category: "Security",
    title: "Privacy & Safety: What We Protect",
    excerpt:
      "A high‑level overview of access control, account protection, and safe collaboration.",
    date: "Apr 2026",
    readTime: "4 min",
    content: [
      "Privacy is a product feature, not a checkbox.",
      "",
      "## What matters most",
      "- Account security (email verification + password reset flow)",
      "- Access control (who can join and who can see content)",
      "- Clear rules for recording and sharing",
    ],
  },
  {
    slug: "product-updates",
    category: "Updates",
    title: "Meetza Updates: What’s New",
    excerpt: "New improvements across meetings, chat performance, and overall experience.",
    date: "Apr 2026",
    readTime: "2 min",
    content: [
      "We’re improving Meetza continuously.",
      "",
      "## Recent highlights",
      "- Better landing navigation",
      "- Improved layouts and responsiveness",
      "- More consistent UI across pages",
    ],
  },
];

