export const BLOG_CATEGORIES = [
  "All",
  "Meetings",
  "Chat",
  "Scheduling",
  "Video Sessions",
  "Security",
  "Updates",
];

export const BLOG_POSTS = [
  {
    slug: "secure-video-meetings",
    category: "Meetings",
    title: "Secure Video Meetings: Best Practices",
    excerpt:
      "How to create, run, and follow up on meetings—with recording, notes, and group access in Meetza.",
    date: "Apr 2026",
    content: [
      "Secure Video Meetings: Best Practices",
      "",
      "## Before the meeting",
      "### Admins and group leaders",
      "- Create the meeting and make sure the details are correct",
      "- Choose whether recording is on or off (Recording ON/OFF) when you create the meeting",
      "- Add notes, decisions, or upload files (e.g., PDFs) while setting it up",
      "- Set it as a one-time meeting or a weekly recurring meeting",
      "- Cancel a weekly series anytime when plans change",
      "- Access stays limited to members of the group",
      "",
      "### Members",
      "- You only join through your group—access is for group members",
      "- Check your camera and microphone before you join",
      "- Join a little early to test your audio",
      "",
      "## During the meeting",
      "### Admins and group leaders",
      "- Keep notes and decisions updated during the meeting",
      "- If recording is on, remind everyone the meeting is being recorded",
      "- Keep screen sharing focused on what the group needs",
      "",
      "### Members",
      "- Join from the chat with Join Meeting, or from your calendar",
      "- Stay muted when you are not speaking to reduce background noise",
      "- Share your screen only when it helps the group",
      "",
      "## After the meeting",
      "### Admins and group leaders",
      "- Documents and resources (notes, decisions, uploads) stay available to the whole group",
      "- If the meeting was recorded, it is published in Video Sessions for all group members automatically",
      "",
      "### Members",
      "- Open documents and resources the team shared from the meeting",
      "- When recording was on, watch the recording in Video Sessions",
    ],
  },
  {
    slug: "group-chat-tips",
    category: "Chat",
    title: "Real‑Time Group Chat in Meetza",
    excerpt:
      "What Meetza’s Messages page actually gives you: groups, live chat, media, meetings, calendar, and notifications.",
    date: "Apr 2026",
    content: [
      "Group chat is powerful when it stays clean and focused. In Meetza, it also connects to meetings, media, and shared resources—here is what you already have in the product.",
      "",
      "## What you already have in Meetza",
      "- Open Messages and pick a group from your chat list to see its conversation",
      "- Messages update in real time while you are in the chat",
      "- Send text from the composer, plus emoji from the emoji picker",
      "- Attach images, videos, audio, or documents, or record a voice message from the attachment options",
      "- Scroll up to load older messages when you need context from earlier",
      "- Edit or delete messages you sent (when the action is available for that message)",
      "",
      "## Meetings and calendar (from chat)",
      "- When a meeting is live for the group, members see Join Meeting and can enter from chat",
      "- Use the calendar in the sidebar to see what is scheduled and join when it is time",
      "",
      "## Media, files, and group resources",
      "- Browse photos, videos, files, and links collected for the group (from messages and shared content)",
      "- Use the right sidebar to jump to group-related sections (including video sessions when available)",
      "- In the expanded group area, upload files or add link resources to the group’s shared content (where your role allows it)",
      "",
      "## Notifications",
      "- Open notifications from the chat experience to catch updates you might have missed",
      "",
      "## Simple habits that match Meetza",
      "- Pair an attachment with a short text line so others know why it matters",
      "- Keep one topic per message when you can—easier to reply and scroll on mobile",
      "- For meetings, use Join Meeting in chat or join from the calendar—same group, same flow",
    ],
  },
  {
    slug: "schedule-meetings",
    category: "Scheduling",
    title: "Calendar & scheduling in Meetza",
    excerpt:
      "Use the Calendar page and the group sidebar to see meetings, filter by group, search, and join when it is time.",
    date: "Apr 2026",
    content: [
      "Meetza does not use a separate “send reminder” wizard in the app—your schedule comes from meetings that are created for your groups. The Calendar and the chat sidebar show what is coming up so you can plan and join.",
      "",
      "## Calendar page",
      "- Open Calendar from the app (when your account can access it) to see your personalized schedule",
      "- Switch views between Day, Week, and Month, or pick a custom date range to focus on specific dates",
      "- Meetings appear with their start and end times and show which group they belong to",
      "- Use Filter to show All groups or narrow the list to one group",
      "- Use Search to find meetings by title",
      "- Join a meeting from the calendar when it is available; the list can refresh when meetings change so you are not stuck on old data",
      "",
      "## While you are in Messages (group chat)",
      "- The sidebar Calendar lists meetings for the group you have open",
      "- When a meeting is live, you can go to it from the chat flow (for example Join Meeting) or use the calendar entry, depending on what the screen shows for that moment",
      "",
      "## How this fits with meeting setup",
      "- One-time and weekly recurring meetings, recording choices, and notes are set when the meeting is created—see the Secure Video Meetings article for that side of the workflow",
      "- The calendar is where you see the result: what is on, when, and for which group",
    ],
  },
  {
    slug: "video-sessions-library",
    category: "Video Sessions",
    title: "Record & Save: Your Video Sessions Library",
    excerpt:
      "Browse group recordings in Video Sessions, save what matters, and use AI summary and transcript on each video.",
    date: "Apr 2026",
    content: [
      "When a meeting is recorded and published to your group, it shows up in **Video Sessions** alongside other uploads. That’s your shared library: one place to open a recording, watch it, and come back later without hunting through chat or links.",
      "",
      "### AI summary for every recording or video",
      "On any video detail page, you can run **AI Summary**. Meetza sends the video to the backend and returns a **written summary** and, when available, a **transcript**—so you can skim what was said without rewatching the whole session. You can pick a language for generation when you start the summary. The result appears in an on-page **AI Summary** panel you can close when you’re done.",
      "",
      "### Save and organize what you keep",
      "Use **Save** on a session to bookmark it for yourself; saved items are easy to find when you need a past standup, training clip, or meeting recap. Clear titles and consistent naming still help everyone in the group scan the list faster.",
      "",
      "### Why it matters",
      "Recordings are only useful if people can find them and understand them quickly. Video Sessions plus **AI summary** turns long calls into something you can search, skim, and share—without replacing the full recording when you need to verify tone or detail.",
    ],
  },
  {
    slug: "privacy-overview",
    category: "Security",
    title: "Privacy & Safety: What We Protect",
    excerpt:
      "A high‑level overview of access control, account protection, and safe collaboration.",
    date: "Apr 2026",
    content: [
      "Privacy is a product feature, not a checkbox.",
      "",
      "## What matters most",
      "- Account security (email verification + password reset flow)",
      "- Access control (who can join and who can see content)",
      "- Clear rules for recording and sharing",
    ],
  },
  {
    slug: "product-updates",
    category: "Updates",
    title: "Meetza Updates: What’s New",
    excerpt: "New improvements across meetings, chat performance, and overall experience.",
    date: "Apr 2026",
    content: [
      "We’re improving Meetza continuously.",
      "",
      "## Recent highlights",
      "- Better landing navigation",
      "- Improved layouts and responsiveness",
      "- More consistent UI across pages",
    ],
  },
];

